#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/pbbuttonsd`
case "$1" in
  start)
    stat_busy "Starting pbbuttonsd"
    [ -z "$PID" ] && /usr/bin/pbbuttonsd -q -d &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/pbbuttonsd.pid
      add_daemon pbbuttonsd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping pbbuttonsd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon pbbuttonsd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
