------------------------------------------------------------------------------
Arch Linux PPC
YABOOT BOOT
created with 'mkbootfs' written by Alexander Baldeck <kth5@archlinuxppc.org>

Press ENTER or type 'arch' to boot the CD.

If you wish to change your defaults to boot into your existing system,
type 'arch initrd=initrd.img <any_other_boot_option>'

Type <tab> if you want to see all available boot options. "-ofonly" signals
that the configuration will not attempt to load a framebuffer driver for your
card. Use those if you have problems with onscreen output.
------------------------------------------------------------------------------

